### ISSUE TITLE
paper about the code

### ISSUE THREAD

**Issue by cploveflower** [Marco-Z/Spoofing-Face-Recognition-With-3D-Masks#2]
hello,Marco-Z!
now I am researching the spoofing detection,do you have any paper about the code that you provide,thang you!

**Comment by Marco-Z** [comment]
Hi,

The repo code is based on the following paper:
> Erdogmus, Nesli, and Sebastien Marcel. "Spoofing face recognition with 3D masks." IEEE transactions on information forensics and security 9.7 (2014): 1084-1097. 

[Here](https://ieeexplore.ieee.org/abstract/document/6810829/) is a link.

Thank you.
