### ISSUE TITLE
3DMAD 

### ISSUE THREAD

**Issue by cploveflower** [Marco-Z/Spoofing-Face-Recognition-With-3D-Masks#4]
Hello!
@Marco-Z 
I'm sorry to distribute you， can you privode the dataset for me?I can't apply it at once because of the
problem of email,can you help me ?
Thank you very much!

**Comment by Marco-Z** [comment]
Hi @cploveflower, unfortunately I don't have access to the dataset anymore.
You can try to contact someone from [idiap](https://www.idiap.ch/en).
Maybe the [authors](mailto://nesli.erdogmus@idiap.ch) or try using their [contact form](https://www.idiap.ch/en/idiap-contact-from).
